### PR TITLE
Add content

### PR DESCRIPTION
**Pull request by obed300**
In this exercise, I consolidated my knowledge on React, components, props, state, and hooks, by following a tutorial.

### CODE REVIEW

**Review by TamaraDimov — COMMENTED** [review]
# Status: REQUIRED CHANGES :recycle: 
### Hi  @obed300   👋 👋 
#### I'm @TamaraDimov , Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights 
✔️ Professional PR. 👍
✔️ No linter errors👍
✔️ Awesome design👍

## Required Changes ♻️

- [ ] It seems that you don't have licensed readme file. I would kindly ask you to add license on your readme file. 
   
   _A well-documented and licensed Readme file can serve as a reference for others who want to use your app.  ✨✨


**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by obed300** [comment]
Thank you for the review. I will do the corrections

**Review by TamaraDimov — APPROVED** [review]
# Status: APPROVED 🟢 

Hi @obed300 ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me  if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by obed300** [comment]
Thank you. I have really learnt a lot from you😊

**Pull request merged**
